# Generated by Django 6.1.1 on 2026-09-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('RECEPCION', '1 - Recepción'), ('RECRIA_1', '2 - Recría Uno (100-150kg)'), ('RECRIA_2', '3 - Recría Dos (150-230kg)'), ('TERMINACION_1', '4 - Terminación Uno (230-400kg)'), ('TERMINACION_2', '5 - Terminación Dos (230-400kg)')], max_length=20, unique=True)),
                ('porcentaje_alimento', models.DecimalField(decimal_places=2, help_text='% sobre peso vivo diario', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caravana', models.CharField(max_length=30, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado?')),
                ('fecha_ingreso_corral', models.DateField()),
                ('kg_ingreso_corral', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kg_actual', models.DecimalField(decimal_places=2, help_text='Peso actual para calcular comida', max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('corral_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion.corral')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.animal')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.vacuna')),
            ],
            options={
                'unique_together': {('animal', 'vacuna')},
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='vacunas',
            field=models.ManyToManyField(blank=True, through='gestion.AplicacionVacuna', to='gestion.vacuna'),
        ),
    ]
