# Generated by Django 6.1.1 on 2026-09-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_actual',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='corral',
            name='porcentaje_alimento',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso_en_movimiento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.animal')),
                ('corral_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='gestion.corral')),
                ('corral_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='gestion.corral')),
            ],
        ),
        migrations.CreateModel(
            name='Pesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesadas', to='gestion.animal')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
