# Generated by Django 6.1.1 on 2026-09-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_animal_castrado_alter_animal_kg_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='corral_destino',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='corral_origen',
        ),
        migrations.RemoveField(
            model_name='pesada',
            name='animal',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='aplicacionvacuna',
            options={'verbose_name': 'Aplicación de Vacuna', 'verbose_name_plural': 'Aplicaciones de Vacunas'},
        ),
        migrations.AlterModelOptions(
            name='corral',
            options={'verbose_name': 'Corral', 'verbose_name_plural': 'Corrales'},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'verbose_name': 'Vacuna', 'verbose_name_plural': 'Vacunas'},
        ),
        migrations.AlterUniqueTogether(
            name='aplicacionvacuna',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False, verbose_name='¿Castrado?'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='corral_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='gestion.corral', verbose_name='Corral Actual'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_ingreso_corral',
            field=models.DateField(verbose_name='Fecha ingreso al corral'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_actual',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kg actual'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_ingreso_corral',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kg ingreso al corral'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numero_caravana',
            field=models.CharField(max_length=30, unique=True, verbose_name='N° Caravana'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacunas',
            field=models.ManyToManyField(blank=True, through='gestion.AplicacionVacuna', to='gestion.vacuna', verbose_name='Vacunas aplicadas'),
        ),
        migrations.AlterField(
            model_name='aplicacionvacuna',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='aplicacionvacuna',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha aplicación'),
        ),
        migrations.AlterField(
            model_name='aplicacionvacuna',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.vacuna', verbose_name='Vacuna'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='nombre',
            field=models.CharField(choices=[('RECEPCION', '1 - Recepción'), ('RECRIA_1', '2 - Recría Uno (100-150kg)'), ('RECRIA_2', '3 - Recría Dos (150-230kg)'), ('TERMINACION_1', '4 - Terminación Uno (230-400kg)'), ('TERMINACION_2', '5 - Terminación Dos (230-400kg)')], max_length=20, unique=True, verbose_name='Corral'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='porcentaje_alimento',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='% Alimento diario'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre vacuna'),
        ),
        migrations.AddConstraint(
            model_name='aplicacionvacuna',
            constraint=models.UniqueConstraint(fields=('animal', 'vacuna'), name='unica_vacuna_por_animal'),
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='Pesada',
        ),
    ]
