# Generated by Django 6.1.1 on 2026-09-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_movimiento_animal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('peso_en_movimiento', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso al mover')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.animal', verbose_name='Animal')),
                ('corral_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='gestion.corral', verbose_name='Corral destino')),
                ('corral_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='gestion.corral', verbose_name='Corral origen')),
            ],
            options={
                'verbose_name': 'Movimiento de Corral',
                'verbose_name_plural': 'Movimientos de Corral',
            },
        ),
        migrations.CreateModel(
            name='Pesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (Kg)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesadas', to='gestion.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Pesada',
                'verbose_name_plural': 'Historial de Pesadas',
                'ordering': ['-fecha'],
            },
        ),
    ]
