# Generated by Django 6.1.1 on 2026-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_movimiento_pesada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='kg_ingreso_corral',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kg ingreso'),
        ),
    ]
