# Generated by Django 6.1.1 on 2026-09-06 15:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_animal_kg_ingreso_corral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.date.today)),
                ('kg_venta', models.FloatField(verbose_name='Kg a la venta')),
                ('precio_kg', models.FloatField(verbose_name='Precio $ por Kg')),
                ('comprador', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='aplicacionvacuna',
            name='unica_vacuna_por_animal',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='vacunas',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corral',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pesada',
            options={},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='castrado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='porcentaje_alimento',
        ),
        migrations.AddField(
            model_name='animal',
            name='numero_electronico',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='corral',
            name='capacidad',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='corral_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_ingreso_corral',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_actual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_ingreso_corral',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numero_caravana',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='corral',
            name='nombre',
            field=models.CharField(choices=[('adaptacion', 'Adaptación'), ('engorde', 'Engorde'), ('terminacion', 'Terminación'), ('enfermeria', 'Enfermería')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='corral_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_destino', to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='corral_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_origen', to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='peso_en_movimiento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesadas', to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='venta',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='gestion.animal'),
        ),
        migrations.DeleteModel(
            name='AplicacionVacuna',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
    ]
