# Generated by Django 6.1.1 on 2026-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_venta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre vacuna')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='numero_electronico',
        ),
        migrations.AddField(
            model_name='corral',
            name='porcentaje_alimento',
            field=models.FloatField(default=3.0, verbose_name='% alimento'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='nombre',
            field=models.CharField(choices=[('adaptacion', 'Adaptación'), ('engorde', 'Engorde'), ('terminacion', 'Terminación'), ('enfermeria', 'Enfermería'), ('recepcion', 'Recepción'), ('recria_1', 'Recría 1'), ('recria_2', 'Recría 2'), ('terminacion_1', 'Terminación 1'), ('terminacion_2', 'Terminación 2')], max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='vacunas_ingreso',
            field=models.ManyToManyField(blank=True, to='gestion.vacuna', verbose_name='Vacunas aplicadas al ingreso'),
        ),
    ]
