# Generated by Django 6.1.1 on 2026-09-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_vacuna_remove_animal_numero_electronico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corral',
            options={'verbose_name': 'Corral', 'verbose_name_plural': 'Corrales'},
        ),
        migrations.AlterField(
            model_name='corral',
            name='nombre',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('recria_1', 'Recría 1'), ('recria_2', 'Recría 2'), ('terminacion_1', 'Terminación 1'), ('terminacion_2', 'Terminación 2')], max_length=20, unique=True),
        ),
    ]
