# Generated by Django 6.1.1 on 2026-09-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_corral_options_alter_corral_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corral',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='kg_ingreso_corral',
            new_name='kg_ingreso',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha_venta',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='animal',
            name='corral_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacunas_ingreso',
            field=models.ManyToManyField(blank=True, to='gestion.vacuna'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='porcentaje_alimento',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='corral_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='corral_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen', to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='kg_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_kg',
            field=models.FloatField(),
        ),
    ]
