# Generated by Django 6.1.1 on 2026-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_corral_options_alter_vacuna_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('macho_entero', 'Macho Entero'), ('macho_castrado', 'Macho Castrado'), ('hembra', 'Hembra')], default='macho_castrado', max_length=20),
        ),
        migrations.AddField(
            model_name='corral',
            name='gdpv_esperado',
            field=models.FloatField(default=0.8, help_text='Ganancia diaria esperada en kg (ej: 0.65)'),
        ),
        migrations.AddField(
            model_name='corral',
            name='peso_entrada',
            field=models.FloatField(default=0, help_text='Peso minimo con el que entra a este corral'),
        ),
        migrations.AddField(
            model_name='corral',
            name='peso_salida',
            field=models.FloatField(default=0, help_text='Peso objetivo para salir de este corral'),
        ),
    ]
