# Generated by Django 6.1.1 on 2026-09-09 17:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_animal_categoria_corral_gdpv_esperado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('muerte', 'Muerte natural'), ('enfermedad', 'Enfermedad'), ('accidente', 'Accidente'), ('robo', 'Robo / Extravío'), ('otro', 'Otro')], default='muerte', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('kg_baja', models.FloatField(help_text='Kg al momento de la baja')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.animal')),
            ],
        ),
    ]
