# Generated by Django 6.1.1 on 2026-09-09 17:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='gdpv_esperado',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='peso_entrada',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='peso_salida',
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_actual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='baja',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baja', to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='baja',
            name='kg_baja',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='baja',
            name='motivo',
            field=models.CharField(choices=[('muerte', 'Muerte'), ('descarte', 'Descarte'), ('enfermedad', 'Enfermedad'), ('otro', 'Otro')], default='muerte', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.animal'),
        ),
    ]
