# Generated by Django 6.1.1 on 2026-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_animal_categoria_remove_corral_gdpv_esperado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('castrado', 'Castrado')], default='macho', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_actual',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_ingreso',
            field=models.FloatField(default=150),
        ),
    ]
