# Generated by Django 6.1.1 on 2026-09-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_animal_categoria_alter_animal_kg_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corral',
            name='dias_objetivo',
            field=models.IntegerField(default=30, help_text='Días para estar listo'),
        ),
        migrations.AddField(
            model_name='corral',
            name='kg_objetivo',
            field=models.IntegerField(default=250, help_text='Kg para estar listo'),
        ),
    ]
