# Generated by Django 6.1.1 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_corral_dias_objetivo_corral_kg_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='corral',
            name='gdpv_esperado',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='corral',
            name='peso_entrada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='corral',
            name='peso_salida',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='corral',
            name='dias_objetivo',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='corral',
            name='kg_objetivo',
            field=models.IntegerField(default=250),
        ),
    ]
