# Generated by Django 6.1.1 on 2026-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_corral_gdpv_esperado_corral_peso_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corral',
            name='porcentaje_alimento',
            field=models.FloatField(default=2.0, verbose_name='% alimento'),
        ),
    ]
