# Generated by Django 6.1.1 on 2026-09-10 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_corral_porcentaje_alimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='peso_en_movimiento',
            field=models.FloatField(default=0),
        ),
    ]
