# Generated by Django 6.1.1 on 2026-09-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_movimiento_options_alter_movimiento_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('castrado', 'Castrado'), ('vaquillona', 'Vaquillona'), ('vaca', 'Vaca'), ('toro', 'Toro'), ('novillo', 'Novillo'), ('macho_entero', 'Macho entero')], default='macho', max_length=15),
        ),
    ]
