# Generated by Django 6.1.1 on 2026-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_animal_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corral',
            name='nombre',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('recria_1', 'Recría 1'), ('recria_2', 'Recría 2'), ('terminacion_1', 'Terminación 1'), ('terminacion_2', 'Terminación 2'), ('venta', 'Venta')], max_length=20, unique=True),
        ),
    ]
