# Generated by Django 6.1.1 on 2026-09-14 15:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_corral_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': '02 Animals'},
        ),
        migrations.AlterModelOptions(
            name='baja',
            options={'verbose_name_plural': 'Bajas'},
        ),
        migrations.AlterModelOptions(
            name='corral',
            options={'verbose_name_plural': '01 Corrals'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha'], 'verbose_name_plural': '05 Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='pesada',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Pesadas'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': '03 Ventas'},
        ),
        migrations.RemoveField(
            model_name='baja',
            name='kg_baja',
        ),
        migrations.RemoveField(
            model_name='baja',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='corral',
            name='kg_objetivo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='comprador',
        ),
        migrations.AddField(
            model_name='baja',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pesada',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo en stock?'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('RECRIA', 'Recría'), ('RECRIA_1', 'Recría 1'), ('RECRIA_2', 'Recría 2'), ('TERMINACION_1', 'Terminación 1'), ('TERMINACION_2', 'Terminación 2'), ('VENTA', 'Venta')], default='RECRIA', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='corral_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='gestion.corral', verbose_name='Corral Actual'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Ingreso Sistema'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_ingreso_corral',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Ingreso a Corral Actual'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_actual',
            field=models.FloatField(blank=True, null=True, verbose_name='Kg Actual'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_ingreso',
            field=models.FloatField(verbose_name='Kg Ingreso'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numero_caravana',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° Caravana'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacunas_ingreso',
            field=models.ManyToManyField(blank=True, to='gestion.vacuna', verbose_name='Vacunas Ingreso'),
        ),
        migrations.AlterField(
            model_name='baja',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='baja',
            name='motivo',
            field=models.CharField(choices=[('MUERTE', 'Muerte'), ('VENTA', 'Venta'), ('OTRO', 'Otro')], default='MUERTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='corral',
            name='capacidad',
            field=models.IntegerField(default=0, verbose_name='Capacidad Max. Cabezas'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='dias_objetivo',
            field=models.IntegerField(default=0, verbose_name='Días Objetivo'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='gdpv_esperado',
            field=models.FloatField(default=0, verbose_name='GDPV Esperado'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre interno'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='peso_entrada',
            field=models.FloatField(default=0, verbose_name='Peso Entrada (Kg)'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='peso_salida',
            field=models.FloatField(default=0, verbose_name='Peso Salida (Kg)'),
        ),
        migrations.AlterField(
            model_name='corral',
            name='porcentaje_alimento',
            field=models.FloatField(default=100, verbose_name='% de Alimento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='corral_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='corral_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='gestion.corral'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='peso_en_movimiento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesadas', to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='peso',
            field=models.FloatField(verbose_name='Peso registrado (Kg)'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.animal', verbose_name='Animal Vendido'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='kg_venta',
            field=models.FloatField(verbose_name='Kilos Vendidos'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Kg'),
        ),
    ]
