# Generated by Django 6.1.1 on 2026-09-14 15:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_alter_animal_options_alter_baja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='kg_baja',
            field=models.FloatField(default=0, verbose_name='Kg a la baja'),
        ),
        migrations.AddField(
            model_name='corral',
            name='kg_objetivo',
            field=models.IntegerField(default=0, verbose_name='Kg Objetivo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('RECRIA', 'Recría'), ('RECRIA_1', 'Recría 1'), ('RECRIA_2', 'Recría 2'), ('TERMINACION_1', 'Terminación 1'), ('TERMINACION_2', 'Terminación 2'), ('VENTA', 'Venta'), ('ternero', 'Ternero'), ('novillo', 'Novillo'), ('vaquillona', 'Vaquillona'), ('vaca', 'Vaca'), ('toro', 'Toro')], default='RECRIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_ingreso_corral',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kg_ingreso',
            field=models.FloatField(default=80, verbose_name='Kg Ingreso'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacunas_ingreso',
            field=models.ManyToManyField(blank=True, to='gestion.vacuna'),
        ),
        migrations.AlterField(
            model_name='baja',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='baja',
            name='motivo',
            field=models.CharField(choices=[('muerte', 'muerte'), ('MUERTE', 'Muerte'), ('VENTA', 'Venta'), ('OTRO', 'Otro')], default='muerte', max_length=20),
        ),
        migrations.AlterField(
            model_name='corral',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corral',
            name='dias_objetivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corral',
            name='gdpv_esperado',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='corral',
            name='peso_entrada',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='corral',
            name='peso_salida',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='corral',
            name='porcentaje_alimento',
            field=models.FloatField(default=2.0, verbose_name='% de Alimento'),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesada_set', to='gestion.animal'),
        ),
        migrations.AlterField(
            model_name='pesada',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='kg_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
