# Generated by Django 6.1.1 on 2026-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_baja_kg_baja_corral_kg_objetivo_alter_animal_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('ternero', 'Ternero'), ('ternera', 'Ternera'), ('novillo', 'Novillo'), ('vaquillona', 'Vaquillona'), ('vaca', 'Vaca'), ('toro', 'Toro'), ('hembra', 'Hembra'), ('mej', 'MEJ')], default='ternero', max_length=20),
        ),
    ]
