# Generated by Django 6.1.1 on 2026-09-12 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('categoria', models.CharField(choices=[('VENTA_HACIENDA', 'Venta de Hacienda'), ('COMPRA_HACIENDA', 'Compra de Hacienda'), ('SANIDAD', 'Sanidad / Vacunas'), ('ALIMENTACION', 'Alimentación'), ('COMBUSTIBLE', 'Combustible'), ('PERSONAL', 'Personal'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': '06 Caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
